---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Download Java
      get_url:
        url: "https://striim-downloads.s3.us-west-1.amazonaws.com/jdk-8u341-linux-x64.tar.gz"
        dest: "/home/jdk-8u341-linux-x64.tar.gz"
